---
mirror_url: "http://archive.apache.org/dist/flink"
version: "0.9.1"
version_for: "bin-hadoop27"
download_path: "/root"
installation_path: "/usr/local"
jobmanager_heap_mb: 256 
taskmanager_heap_mb: 512 
taskmanager_numberOfTaskSlots: "{{ ansible_processor_count * ansible_processor_cores }}"
parallelization_degree_default: "{{ (ansible_processor_count * ansible_processor_cores * groups['slaves']|count / 2)|int }}"
number_of_taskmanagers: "{{ groups['slaves']|count }}"
ram_per_task_manager: 768

