---

  - name: Fix locale problem.
    command: update-locale LANGUAGE="en_US.UTF-8" LC_ALL="en_US.UTF-8"

  - name: Copy sources list.
    copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0640
    when: "'slaves' in group_names"

  - name: Set hostname
    hostname: name={{ inventory_hostname | replace(".vm.okeanos.grnet.gr",".local") }}
    when: "'slaves' in group_names"

  - name: Copy hosts file.
    template: src=hosts.j2 dest=/etc/hosts backup=no owner=root group=lambda mode=0750

  - name: Upgrade packages.
    apt: upgrade=dist update_cache=yes
    environment: proxy_env
    when: "'slaves' in group_names"

  - name: Install the latest Java 7.
    apt: name=openjdk-7-jdk state=latest install_recommends=no update_cache=yes
    environment: proxy_env

  - name: Copy environment file.
    template: src=environment.j2 dest=/etc/environment backup=no owner=root group=lambda mode=0750

  - name: Install sudo.
    apt: name=sudo state=latest
    environment: proxy_env

  - name: Add hduser to sudo group.
    user: name=hduser group=sudo

  - name: Add flink user to sudo group.
    user: name=flink group=sudo

  - name: Add kafka user to sudo group.
    user: name=kafka group=sudo

  - name: Install supervisord with apt.
    apt: name=supervisor state=latest
    environment: proxy_env

  - name: Configure supervisord for master.
    template: src=supervisord-master.conf.j2 dest=/etc/supervisor/supervisord.conf owner=root group=root mode=0600
    when: "'master' in group_names"

  - name: Configure supervisord for slaves.
    template: src=supervisord-slaves.conf.j2 dest=/etc/supervisor/supervisord.conf owner=root group=root mode=0600
    when: "'slaves' in group_names"

  - name: Start supervisord on every node.
    command: supervisord -c /etc/supervisor/supervisord.conf --logfile=/root/supervisord.log

  - name: Distribute hduser ssh key to all nodes.
    authorized_key: user=hduser key="{{ lookup('file', '/tmp/fetched/hduser_id_rsa.pub') }}"

  - name: Distribute flink ssh key to all nodes.
    authorized_key: user=flink key="{{ lookup('file', '/tmp/fetched/flink_id_rsa.pub') }}"

