---

  - name: Create users for each application.
    include: users.yml

  - name: Generate ssh key for hduser.
    shell: cat /dev/zero | ssh-keygen -q -N ""
    args:
      creates: /home/hduser/.ssh/id_rsa.pub
    tags:
      - image-configure

  - name: Fetch id_rsa.pub file from hduser user.
    fetch: src=/home/hduser/.ssh/id_rsa.pub dest=/tmp/fetched/hduser_id_rsa.pub flat=yes
    tags:
      - image-configure

  - name: Generate ssh key for flink user.
    shell: cat /dev/zero | ssh-keygen -q -N ""
    args:
      creates: /home/flink/.ssh/id_rsa.pub
    tags:
      - image-configure

  - name: Fetch id_rsa.pub file from flink user.
    fetch: src=/home/flink/.ssh/id_rsa.pub dest=/tmp/fetched/flink_id_rsa.pub flat=yes
    tags:
      - image-configure

  - name: Set up ssh config for root user.
    template: src=ssh-config.j2 dest=/root/.ssh/config owner=root group=root mode=664
    tags:
      - image-configure

  - name: Set up ssh config for hduser user.
    template: src=ssh-config.j2 dest=/home/hduser/.ssh/config owner=hduser group=lambda mode=600
    tags:
      - image-configure

  - name: Set up ssh config for flink user.
    template: src=ssh-config.j2 dest=/home/flink/.ssh/config owner=flink group=lambda mode=600
    tags:
      - image-configure

  - name: Copy Lambda Instance init script.
    template: src=lambda-init.j2 dest=/etc/init.d/lambda-init owner=root group=lambda mode=0740

    # The Lambda services will be started individually during the execution of the playbooks.
    # The lock file neends to be created so that lambda-init script is aware that there is
    # a Lambda Instance running.
  - name: Create Lambda Instance lock file.
    file: path=/root/lambda-lock state=touch owner=root group=lambda mode=0640
    tags:
      - image-configure

  - name: Put lambda init script on boot and shutdown sequence.
    command: update-rc.d lambda-init defaults
    tags:
      - image-configure

  - name: Make sure the init script is started.
    service: name=lambda-init state=started
    tags:
      - image-configure

  - name: Set PATH environment variable for flink user
    lineinfile: destfile="/home/flink/.bashrc"
              regexp="^PATH"
              line="PATH=$PATH:{{ flink_home }}/bin:{{ hadoop_home }}/bin"
              state=present
              insertafter=EOF
