---

- name: Set hadoop env
  lineinfile: dest=/usr/local/hadoop/etc/hadoop/hadoop-env.sh regexp="^export JAVA_HOME=" line="export JAVA_HOME=/usr/"
  tags: env

- name: Copy slaves configuration
  template: src=../templates/usr/local/hadoop/etc/hadoop/slaves.j2
            dest=/usr/local/hadoop/etc/hadoop/slaves
            owner=root group=root mode=0644
  tags: slaves

- name: Copy core configuration
  template: src=../templates/usr/local/hadoop/etc/hadoop/core-site.xml.j2
            dest=/usr/local/hadoop/etc/hadoop/core-site.xml
            owner=root group=root mode=0644
  tags: core

- name: Copy hdfs configuration
  copy: src=../files/usr/local/hadoop/etc/hadoop/hdfs-site.xml
        dest=/usr/local/hadoop/etc/hadoop/hdfs-site.xml backup=no
        owner=root group=root mode=0644
  tags: hdfs

- name: Copy yarn configuration
  template: src=../templates/usr/local/hadoop/etc/hadoop/yarn-site.xml.j2
            dest=/usr/local/hadoop/etc/hadoop/yarn-site.xml
            owner=root group=root mode=0644
  tags: yarn
