site_name: ~okeanos Lambda Instance
pages:
  - Home: index.md
  - Authentication: Authentication.md
  - List Lambda Instances: LambdaInstanceList.md
  - Details of a Lambda Instance: LambdaInstanceDetails.md
  - Destroy a Lambda Instance: LambdaInstanceDestroy.md
  - Start a Lambda Instance: LambdaInstanceStart.md
  - Stop a Lambda Instance: LambdaInstanceStop.md
  - Get a status of a Lambda Instance: LambdaInstanceStatus.md
  - Manage your apps: Upload.md

theme: readthedocs

